// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IGroth16Verifier
 * @notice Interface for the on-chain Groth16 ZK proof verifier.
 *         Generated by snarkjs `zkey export solidityverifier`.
 */
interface IGroth16Verifier {
    /**
     * @notice Verify a Groth16 proof against public inputs
     * @param proof      ABI-encoded proof (a, b, c points)
     * @param pubInputs  Array of public input field elements
     * @return valid     True if the proof is valid
     */
    function verifyProof(
        bytes calldata proof,
        uint256[] memory pubInputs
    ) external view returns (bool valid);
}
