// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IGroth16Verifier} from "../interfaces/IGroth16Verifier.sol";

/**
 * @title MockZKVerifier
 * @notice Mock verifier for testing. Always returns true.
 *         In production, this is replaced by the real Groth16 verifier
 *         generated by snarkjs.
 */
contract MockZKVerifier is IGroth16Verifier {
    bool public shouldVerify = true;

    function verifyProof(
        bytes calldata /* proof */,
        uint256[] memory /* pubInputs */
    ) external view override returns (bool) {
        return shouldVerify;
    }

    /// @notice Toggle verification result for testing
    function setShouldVerify(bool _should) external {
        shouldVerify = _should;
    }
}
