canton {
  participants {
    vaeb_participant {
      storage.type = memory
      admin-api.port = 5012
      ledger-api.port = 5011
      http-ledger-api-experimental {
        server {
          address = "0.0.0.0"
          port = 7575
        }
        allow-insecure-tokens = true
      }
    }
  }
  domains {
    vaeb_domain {
      storage.type = memory
      public-api.port = 5018
      admin-api.port = 5019
    }
  }
  features.enable-testing-commands = yes
}
